### ISSUE TITLE
Metamask not detected

### ISSUE THREAD

**Issue by elielnfinic** [matter-labs/dapp-portal#158]
Hi everyone, 

I don't know why I am having this issue but I thought it is important to share this issue.
I have Metamask installed in `Chrome(Version 122.0.6261.69 (Official Build) (arm64))` browser but the portal is not detected that I have it. I am using `Mac OS Sonoma 14.1.1`. 

You can see here 
<img width="754" alt="Screenshot 2024-02-28 at 7 00 52 in the evening" src="https://github.com/matter-labs/dapp-portal/assets/46634774/26d1b9db-85d9-47bd-845b-3eddfba087a9">

Thank you.

Here are more screenshots : 

![image](https://github.com/matter-labs/dapp-portal/assets/46634774/85f16fd7-59b6-4b16-9103-1ff9596d7203)

![image](https://github.com/matter-labs/dapp-portal/assets/46634774/cebbd0fe-9693-4b50-ae23-ac7db5b6cae9)

**Comment by elielnfinic** [comment]
Hey @JackHamer09 , thanks for the clarification.

After adding the zkSync network, Metamask was detected.

I suggest that you trigger adding the network if it is not available on the wallet. What do you think?

**Comment by JackHamer09** [comment]
> After adding the zkSync network, Metamask was detected.

I don't really think this is related. Any app you connect to can't know which chains you have in your wallet.

> I suggest that you trigger adding the network if it is not available on the wallet.

There is already such mechanism in place. You can also click the button in the footer to add zkSync network (visible when wallet is connected and some other chain is selected)
